# Generated by Django 2.2.5 on 2021-06-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fromapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='musicians',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('instrument', models.CharField(max_length=30)),
            ],
        ),
    ]
